### ISSUE TITLE
Effect of simulated restarts to be explained

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1018]
Any idea why we see the (slight) bump beyond the maximum budget at `10^5` and `10^6`? This is random search on all `bbob-biobj` functions. 
<img width="1049" alt="screen shot 2016-05-12 at 13 04 43" src="https://cloud.githubusercontent.com/assets/7316439/15217377/973b3916-185b-11e6-9560-008d9195d369.png">

**Comment by loshchil** [comment]
it might be related to the discretization/rounding of target values, the
more precise it is the smaller the bump will be?

**Comment by nikohansen** [comment]
The data displayed are based on a (structured) set of runtimes. They could, in principle, come about with any set of target values. So the question remains, what would be the property on the set of runtimes which makes the bump appear or disappear, or is there any such property?

**Comment by loshchil** [comment]
if there are no bumps for single-objective problems, they might be due to
the use of hypervolume

**Comment by nikohansen** [comment]
We do see bumps for non-random search algorithms, and they are entirely understandable. Restarting an stagnating algorithm can be very helpful to hit more targets quicker. But why do we see a bumps (and indeed also smaller bumbs), when each evaluation is done without exploiting any prior knowledge? 

Maybe because the first evaluation is done in the domain middle?

**Comment by loshchil** [comment]
it might be because of hypervolume or/and some little bug but I don't see
how exactly this may happen

**Comment by nikohansen** [comment]
Given the first evaluation is not the domain middle, I more and more tend to believe that this must be a bug.

**Comment by nikohansen** [comment]
We should 1) replicate the result, in particular comparing with and w/o the first evaluation in the domain middle. 2) check whether this can only be seen in the MO case. 3) investigate the normalization/computations when at least one run is unsuccessful.

**Comment by brockho** [comment]
I will do some runs (SO and MO) w/ and w/o evaluating the domain middle as first point to answer 1) and 2).

**Comment by brockho** [comment]
Here are the promised results. First a comparison of random search on the sphere/sphere problem of the `bbob-biobj` suite in different dimensions (from top left to bottom right: 2-D, 5-D, 10-D, 20-D):

![rs-mo-spheresphere](https://cloud.githubusercontent.com/assets/13706996/15520509/217a89ba-2207-11e6-8a97-55ebe40f771c.png)

In blue, we see the standard random search within `[-5,5]^n`. In pink, the same algorithm but which, in addition, evaluates the domain middle (i.e. the coordinate system origin) as the first solution.

And here the same for the single-objective sphere function of the `bbob` suite:

![rs-so-sphere](https://cloud.githubusercontent.com/assets/13706996/15520839/6d2b579e-2208-11e6-9c77-76c886ca69c4.png)

@nikohansen: If needed, I can run the algorithms for `10^5n` or even `10^6n` function evaluations...

**Comment by nikohansen** [comment]
Hard to say whether the bump is there in these figures. Apparently we need more data to reduce the noise if we want to see the bump. 

> [I took out the single-objective plots because there is obviously a bug in the code generating them]

What is the bug?

**Comment by brockho** [comment]
@anneauger and myself finally investigated this issue again more carefully. It turns out that the problem is most likely a big discrepancy between the difficulties of instances. The bumps on random search data is much more pronounced in lower dimension and on functions where the difficulties of instances are large. Let us have, for example, a look at a random search within `[-4,4]` (together with DEMO and HMO-CMA-ES for comparison) on the separable ellipsoid/attractive sector function (f12) in 2-D for all 10 instances. The two plots below show all targets (above) and only the first twenty easiest targets (`10 ** np.arange(0, -2.0, -0.1)`, below):

![bump-explained-alltargets](https://cloud.githubusercontent.com/assets/13706996/16879964/2e2f6066-4ab3-11e6-8853-1e9799817ad9.png)

![bump-explained-20targets](https://cloud.githubusercontent.com/assets/13706996/16879969/3572c1e2-4ab3-11e6-834f-cc2ea5e5a0b4.png)

Compared to the plots on f1 in one of my above posts, the bump is more than obvious to see here and these are the corresponding runtimes to reach the target precision 0.02511886 (one that is among the most difficult ones in the 20 targets plot above):

| instance | RS-5 | HMO-CMA-ES | DEMO |
| -------- |:-----:|:-----:|:-----:|
| 1 | 252 | 167 | 299
| 2 | 58 | 9 | 7 |
| 3 | 14 | 26 | 5 |
| 4 | inf* | 818 | 1004 |
| 5 | 5427 | 264 | 528 |
| 6 | 188 | 128 | 239 |
| 7 | inf* | 74 | 215 |
| 8 | 23 | 40 | 18 |
| 9 | 6197 | 203 | 776 |
| 10 | 478 | 92 | 335 |
| | * max runtime: 1e6*n | | |

The large variance in runtime among the runs is therefore (most likely) the cause for the bumps in the ECDF graphs: since a simulated restart will pick for RS-4 with 80% probability a short run as the second one, many simulated runs will be just a bit longer than the unsuccessful which gives the quick increase in the ECDF right after the cross.

**Comment by brockho** [comment]
It opens up the question whether the notion of instances makes still sense in the case of the `bbob-biobj` test suite...

**Comment by loshchil** [comment]
Very convincing explanation.

**Comment by nikohansen** [comment]
FTR, for the above reasons we decided to bypass bootstrapped simulated restarts in the bi-objective case.
