### ISSUE TITLE
entry point for browsing

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1028]
In order to make it easier to find the entry point for browsing in a `ppdata` output folder, I suggest that we have an `index.html` file. It is probably best if this is just a copy of the current entry file, in order to remain fully backwards compatible.

**Comment by dtusar** [comment]
The entry point is now the `index.html` file. The `ppdata` file is still there (and working) but it contains an explanation that `index.html` should be used.

**Comment by nikohansen** [comment]
I have an example from the large-scale setting where I only see `templateBBOBarticle.html`. Is this still an issue?

**Comment by dtusar** [comment]
I checked the data in the mentioned issue. The `largescale51.zip` file in the opening comment contains only the single algorithm folder. The `ppdata.html` (or now `index.html`) is located one folder higher, so I would presume that it just wasn't included in the `zip`. Is this correct @NDManh ? You can see that the `ppdata.zip` file in a later comment contains also the `ppdata.html` file.

**Comment by NDManh** [comment]
@dtusar `...it just wasn't included in the zip. Is this correct @NDManh ?`
Yes, it's correct. The `largescale51.zip` is inside a folder higher (obtained from post processing many datasets). I posted only `largescale51.zip` because the folder `ppdata` is quite big, and the the issue is related to this `largescale51.zip`.

The `ppdata.html` file is contained in `ppdata` folder as usual.

**Comment by nikohansen** [comment]
OK, thanks for the clarification.
