### ISSUE TITLE
Figures generation in Post-processing

### ISSUE THREAD

**Issue by strickler** [numbbo/coco#1045]
Dear all,

I noticed that the post-processing only generates figures for 05 and 20 dimensions for each algorithm in "templateBIOBJmultiple.tex" and the "ppdata.html". 
I was wondering if you can point out in coco code to change the post-processing to generate figures for the entire set of dimensions. Or, can you release a new coco version containing this 'new' feature?

Thanks in advance

**Comment by brockho** [comment]
Hi,

Many thanks for reporting your two issues. Let me start with answering this one.

The place you want to check is the file [`genericsetting.py`](https://github.com/numbbo/coco/blob/master/code-postprocessing/bbob_pproc/genericsettings.py)  in which we have the variables `rldDimsOfInterest` for the ECDF plots and `tabDimsOfInterest` for the tables that indicate the dimensions for which plots are produced. Unfortunately, with the current version, you will not be able to see other dimensions than 5 and 20 in the html and LaTeX output. For the former, this must be considered a bug while for the latter, we will most likely not be able to produce LaTeX code that works with all dimensions because it will need some ugly switches in the LaTeX code as the LaTeX code is (for now) mostly static.

Including the dimensions of your choice in the above mentioned variables, however, produces the pdf and svg files for me (latest release) such that you can look at and include them in LaTeX by hand if you wish.

**Comment by strickler** [comment]
Thanks for the support,
I tried the smallest values (2,3) for the `rldDimsOfInterest` and  `tabDimsOfInterest` variables that you recommend. Well, for the LaTeX output it works, but for the html output do not. In _ppdata.html_ I 
entered in the _Runtime for selected targets and f-distributions_ link, then it does not appears any figure (ECDF), and the title are like follows (1-separable 1-separable in 5-D and 20-D).
There is something that I am missing? 

Thanks again.

**Comment by dtusar** [comment]
The values `rldDimsOfInterest` and `tabDimsOfInterest` now affect also the figures/tables  in `html`. It will be available in the next release.
