### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by phrsampaio** [numbbo/coco#1066]
I suggest to not use the variable names "function" and "function_idx" to refer to optimization problems in Coco. That brings up confusion, specially for suites of constrained problems. A problem is composed of one or more objective functions and possibly one or more constraint functions; thus it would make more sense to use names such as "problem" and "problem_idx" for the coco problems. The variable "problem_index", which is currently used as an index to the **parametrized** problem, could then be renamed to "param_problem_index" or something similar.

Another point is related to the removal of the word "objective" from the conventional term "objective function" throughout the code, which causes more confusion as constraints are also functions themselves. Such changes in the terminology would also be helpful for writing the documentation of the suite of constrained problems as well as other suites in the future.

**Comment by ttusar** [comment]
I guess we do have a terminology problem since I don't understand what you mean :)

"function" and "function_idx" already don't refer to optimization problems, but the functions that constitute the problems (a single-objective problem is a function instantiated with an instance and a dimension, a bi-objective problem consists of two (possibly different) functions instantiated with an instance (possibly different for each function) and a dimension). "problem" and "problem_index" (I see we have some inconsistency in the "index" vs. "idx" naming) are already used to denote COCO problems. 

What is a **parametrized** problem?

> Another point is related to the removal of the word "objective" from the conventional term "objective function" throughout the code, which causes more confusion as constraints are also functions themselves.

This sounds a reasonable thing to do for functions/variables that can be interpreted as either objectives or constraints, but I have a hard time finding them. The term "objective function" is not really present in the code, could you be more specific?

**Comment by phrsampaio** [comment]
> ...a single-objective problem is a function instantiated with an instance and a dimension...

That is the point. An optimization problem shouldn't be defined as a function. As I said before, it is composed of one or more objective functions and possibly one or more constraint functions. A definition for a "single-objective problem" should encompass unconstrained and constrained problems (the same for the multiobjective case), which is not the case. In the suite of constrained problems, the variable "function" ranges from 1 to 48, since there are 48 constrained problems. In other words, the variable "function" is being used to refer to optimization problems, which does not seem the right way. Since the name "problem" is already being used for Coco problems, another one could be used in this case.

> What is a parametrized problem?

By considering an optimization problem as [objective function(s), constraint(s)], the parametrized problem would mean a problem with parameters such as dimension, instance and identifier, in a way similar to how "functions" are defined in [http://numbbo.github.io/coco-doc/#functions-instances-problems-and-targets](url).

> The term "objective function" is not really present in the code, could you be more specific?

It is not present in the code, and that is the issue. For instance, a function called coco_evaluate_function() that is used to evaluate objective functions could be renamed to coco_evaluate_objective_function() to avoid ambiguity. The same for the member evaluate_function in coco_problem_s struct.

**Comment by ttusar** [comment]
OK, so the problem (pun intended) is that you need to have two names for something that is now called a problem, one that would describe a combination of functions and constraints, and another that would describe the final "parametrized" problem that should be solved by an optimizer. [We also have a third sense of the word problem that includes targets, but let's keep this one out of this discussion.] Since all existing documentation uses "problem" in this second sense, I think we should leave this one alone and find a different term for the combinations of functions and constraints. Why not call them just **combinations**?

You are using the terms functions and constraints all the time without any ambiguity. So why is there some ambiguity when we say `coco_evaluate_function()` and `coco_evaluate_constraint()`?

**Comment by nikohansen** [comment]
> A definition for a "single-objective problem" should encompass unconstrained and constrained problems (the same for the multiobjective case), which is not the case. 

I agree. Why is it not the case? The `coco_problem_t` type is supposed to be a constrained or unconstrained single- or multi-objective problem. 

> In the suite of constrained problems, the variable "function" ranges from 1 to 48, since there are 48 constrained problems.

Why don't we call them _constrained functions_ rather than constrained problems? I believe there are more than 48 (constrained) problems in the suite.

> a function called coco_evaluate_function() that is used to evaluate objective functions could be renamed to coco_evaluate_objective_function() to avoid ambiguity.

We are often equating function to be objective function. I understand the ambiguities and thought about them already. The correct name would even be `coco_evaluate_problem`, as we consider a function to be instantiated first into a problem before we can evaluate it, right? Given that evaluate function is a rather unique `C`-function (another ambiguity), I don't think this renaming effort should really be necessary, and it would brake lots of code. 

> find a different term for the combinations of functions and constraints. Why not call them just combinations?

Why not call them constrained functions?

**Comment by ttusar** [comment]
> Why not call them constrained functions?

Sounds good to me.

**Comment by phrsampaio** [comment]
Indeed, calling them constrained functions rather than constrained problems seems to be the best alternative as it would change nothing in the code except some comments. In this case, sphere with 1 linear constraint is considered a different constrained function from sphere with 2 linear constraints, for instance.

> I believe there are more than 48 (constrained) problems in the suite.

I was not considering the parameters dimension and instance as in the definition of a problem in Coco. I meant that there are 48 constrained functions. 

It seems to me that the issue has been resolved. Thanks for the helpful comments.
