### ISSUE TITLE
Display information about target values

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1122]
Proposal: display smallest and largest target/budget (for RL-based targets) and the number of targets (e.g. like `targets:1e-8[51]1e2`, `target RLs:0.5[5]50D`), e.g. at the same place where currently "`absolute targets`" is displayed in the figures.

**Comment by brockho** [comment]
Related to #1027

**Comment by brockho** [comment]
This issue shall be solved now with the latest push to the development branch (0d59ff7). I opted for a slightly different display to be more consistent with previous already existing displays and to hopefully be a bit more understandable for the user. Instead of the suggested above, I display now `51 targets in 1e-8..1e2` and `5 target RLs/dim: 0.5..50` respectively.

Comments are always welcome...
