### ISSUE TITLE
COCO WARNING: transform_vars_affine(): 'best_parameter' not updated, set to NAN

### ISSUE THREAD

**Issue by EoghanRussell** [numbbo/coco#1125]
Hi Guys,
I am getting a number of these warnings for various tests but also this appears before the algorithm is initialised. Debugging it I can see that these happen @ main(budget, max_runs, current_batch, number_of_batches)
Can anyone help shed some light on this please? 
Many thanks

**Comment by nikohansen** [comment]
I believe these warnings should not visible to the regular user. I also find them irritating and annoying.

**Comment by ttusar** [comment]
What do you propose to do? They could be "downgraded" to the info or debug level, but I always thought we don't want this (out of sight, out of mind).

**Comment by EoghanRussell** [comment]
Hi Guys,
Are these something that I should be worried about affecting my results?

**Comment by brockho** [comment]
@EoghanRussell: To the best of our knowledge, the warnings should not affect your results since in the single-objective case, the best_parameter values are not used and the current bi-objective test suite does not use the functions where the warning occurs, see also the discussion on the earlier issue #814 of the same topic.

**Comment by brockho** [comment]
@ttusar: I discussed with @nikohansen independently of your answer offline one hour ago and we agreed that the change to info or debug level is the way to go. Since we have the open issue(s) here in the issue tracker, I don't think that we will forget.

In any case, the issue will become critical as soon as we go for the planned extension of the `bbob-biobj` test suite to contain also all other, currently missing `bbob` function combinations where both objectives are the same.

**Comment by EoghanRussell** [comment]
Hi @brockho,
Once again thanks for the quick and thoroughly reply on this. 
Much Appreciated.

**Comment by brockho** [comment]
The corresponding message is now set to `debug` in the development branch such that it is not displayed by default when running the example experiment with the `bbob` suite anymore. However, we'll keep the issue open with #814.
