### ISSUE TITLE
scaling factor for linear constraints

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1191]
Currently, the norm of the gradient of the linear constraints is distributed as `10 * ||N_i(0, I)||` drawn anew for each constraint `i`.^1 As this is a rather limited variation, I would propose

```
   10**U[0,1] * ||N_i(0, I)|| * 10**U_i[0,2]
```

where U[a, b] is uniform in [a,b] and only U_i is drawn for each constraint individually.

Rationale: the variation should neither be rather negligible (like a factor of 3), nor very demanding (like a factor of 1000). With the above setting, the typical factor between 2 constraints is 10, the maximal factor is 100. Overall the geometric average factor is `100^(1/2)` (was 10 before). We might consider using different settings, e.g., for the case of `n+1` constraints using, say, `U_i[0,1]` instead.

^1: See `linear_cons_norm` e.g. at https://github.com/numbbo/coco/blob/development-constraints/code-experiments/src/suite_cons_bbob_problems.c#L145 and at https://github.com/numbbo/coco/blob/902bb99653137310d7ab7495fbb4d33032467c47/code-experiments/src/c_linear.c#L395

**Comment by phrsampaio** [comment]
Scaling updated. The random number 10**U[0,1] is computed in c_linear_cons_bbob_problem_allocate(), the central function in c_linear.c that stacks all the constraints after calling c_linear_single_cons_bbob_problem_allocate(), which builds each constraint individually.  The random number  10**U_i[0,2], in turn,  is calculated in c_linear_single_cons_bbob_problem_allocate() since it depends on the constraint number. In the code, 10**U[0,1] and 10**U_i[0,2] are called 'factor1' and 'factor2', respectively.

**Comment by nikohansen** [comment]
What do you think about using `U_i[0,1]` iff we have `n+1` constraints?

**Comment by phrsampaio** [comment]
I don't see the reason to have `n+1` constraints as a particular case, but I might be missing something. What is the rationale behind it? In cases where `n` is large, I see no problem of still having a wide scaling range for the gradients. But if the reason is just to bring the dimension into play, then I would agree that such a "formula" for the gradients would be even more dynamic.

**Comment by nikohansen** [comment]
the reason is (1) to create a larger variation of test functions, and (2) that `n-1` and `n+1` are somewhat quite similar for large `n` anyway. Now, if an algorithm becomes much better for `n+1` constraints, we know that it is sensitive so scaling of the constraints. If it becomes much worse, we know it is sensitive to having more than `n` constraints.

**Comment by phrsampaio** [comment]
Yes, sensitiveness to scaling should be tested indeed. I will do the modifications.

**Comment by phrsampaio** [comment]
If an algorithm becomes much better for `n+1` constraints, we may not be able to know the reason due to the fact that the constraints are randomly generated: the feasible sets for `n-1` and `n+1` constraints are different as the constrained function identifiers are considered in the building process; so being better for `n+1` constraints might be due to a more favorable (with better shape) feasible set rather than scaling.

**Comment by nikohansen** [comment]
AFAICS, the same argument could be made w.r.t. different functions, that is, the algorithms is better on the sphere than on the ellipsoid, because the sphere constraints have been sampled more favorably, am I wrong?

Given we have 15 instances, this is a quite unlikely event though, am I wrong?

**Comment by phrsampaio** [comment]
> Given we have 15 instances, this is a quite unlikely event though, right?

The number of instances seems a good argument.

**Comment by nikohansen** [comment]
Can't this issue be close?

**Comment by asmaatamna** [comment]
It can.
