### ISSUE TITLE
interface.c is cluttering git diff

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1222]
The `interface.c` file in `build/python/cython` is generated by cython from `interface.pyx`, when the latter is changed and then `cocoex` is rebuilt. This makes a `git diff` command in effect unusable (for me), because it becomes cluttered with useless information. 

Any suggestions how to go about this problem?

**Comment by brockho** [comment]
If `interface.c` is generated anyway from `interface.pyx`, do we really need to keep the former in the repository anyway? Or do we have it in the repository in order to remove dependencies to `cython` for the normal user?

And what exactly is the problem with the `diff`? Is it the sheer size of the `interface.c` and the large amount of changes? Since I use Tortoise under Windows, I do not have such problems: I checked the latest diffs on that file and it looks readable to me.

**Comment by nikohansen** [comment]
> Or do we have it in the repository in order to remove dependencies to cython for the normal user?

That is exactly the idea.

> And what exactly is the problem with the diff?

In the terminal, I have to scroll through the useless and (very) long diff of `interface.c`. Or I would have to invoke a `diff` on each changed file individually (thereby avoiding `interface.c`), which I don't find too practical either.

**Comment by nikohansen** [comment]
A workaround is to recover the previous version of the `interface.c` file:
```
rm interface.c
git checkout -- interface.c  # checkout only one file from the current branch
```
