### ISSUE TITLE
online data archives folder name convention

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1233]
This is how it looks like currently: 
<img width="381" alt="screen shot 2016-11-29 at 15 53 46" src="https://cloud.githubusercontent.com/assets/7316439/20714360/177deb12-b64c-11e6-9225-e7a61a78c48c.png">

Shouldn't we rename `bbob-biobj-2016` to `2016-bbob-biobj`? Do we have dependencies which would brake? 

Even after this, the naming convention is inconsistent, as we have noiseless and noisy testbeds mixed. How about to have for each year/event also a subfolder for each testbed?

**Comment by brockho** [comment]
I agree that this is not consistent. Your suggestion looks fine.

The only dependency I see for the moment is in the tests, because the continuous integration tests of the postprocessing fetch the data from these folders. But this should be simple to fix. If we also decide to restructure the older years' folders, we have to update the wiki as well where the data is referenced.

Maybe we can do the renaming in two steps: first the `bbob-biobj-2016` renaming into `2016-bbob-biobj` with the lesser impacts and then the cleaning up of the rest. You might see that the 2010 and 2012 data is still not there (but on the `lri.fr` server) - so this is yet another long-open issue on my TODO list.

**Comment by loshchil** [comment]
I believe that I downloaded tens of BBOB algorithms about 5-10 times since 2010. Mainly because I used different machines or needed different algorithms or just wanted to make sure I consider all algorithms. 
It might be useful if the post-processing script would allow to download (if not yet downloaded) algorithms by group/type, venue, year, etc with something like 
`download destdir=./algorithms/, testbed=noiseless_singleobj(or noisy_singleobj, or biobj, ..., or *=any), year=2016(or 2015, ... , or *=any)`
or 
`download destdir=./algorithms/, --noise-less --biobj --year2016`

**Comment by nikohansen** [comment]
Right, this was already in the cards for some time, even though I believe there has been no specific issue yet.

This looks like a good point in time to encourage Python shell usage, that is, the `download` function becomes accessible (only) via `cocopp.download`, i.e. from the system shell like
```
python -c "import cocopp; cocopp.download(...)"
``` 

It looks also like a good point in time to fix a testbed name like `bbob-noisy`.

**Comment by brockho** [comment]
see #1128

**Comment by brockho** [comment]
I started to address this issue by moving the biobjective data to the `bbob-biobj/2016/` folder and updated the postprocessing tests accordingly.

**Comment by brockho** [comment]
update: the 2010 and 2012 data has now been moved from the `lri` to the `GForge` server.

**Comment by brockho** [comment]
All data is now available via the new folder structure:
```
|
|--- bbob
|     |
|     |--- 2009
|     |--- 2010
|     |--- 2012
|    ...
|--- bbob-biobj
|     |
|     |--- 2016
|
|--- bbob-noisy
|     |
|     |--- 2009
|     |--- 2010
...
```
Old data folders have been renamed to `OLDNAME-DEPRECATED` but stay for some time at the same place for an easier recovery of the old state.

All tests on our CI run through again as well after the tests have been adapted.
