### ISSUE TITLE
Example experiment for 3+ test suites

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1244]
Since with the `bbob-largescale` test suite we will have soon 3+ test suites that need different observers, dimensions, etc. it might be useful to provide in the various example experiments files all provided use cases:

```
suite = coco_suite(suite_name, "year: 2017", "dimensions: 2,3,5,10,20,40");
/* Use the following instead for the bbob-largescale test suite*/
/* suite = coco_suite(suite_name, "year: 2017", "dimensions: 20,40,80,160,320,640"); */
```
similar to how we already do for the 
```
example_experiment("bbob", "bbob", random_generator);
```
and
```
example_experiment("bbob-biobj", "bbob-biobj", random_generator);
```
part.

**Comment by nikohansen** [comment]
> that need different observers, dimensions, etc
just to be on the same page, the default use-case is the one which provides empty string arguments, right?

**Comment by brockho** [comment]
In the `C` code, the current default is to detail the 2016 main use case with `year` and `dimensions` provided explicitly. Given that we can often not remember ourselves how to set these options, it is  probably the best to keep the default with the options? But I see the problem that this might break the code if we do slight changes to the setting (e.g. changing from the current test suites to a largescale one).

**Comment by nikohansen** [comment]
> Given that we can often not remember ourselves how to set these options, it is probably the best to keep the default with the options?

Forcing options is IMHO not a good way to improve documentation.

To remember the syntax of non-default use cases a link to the documentation is probably helpful, e.g.
http://numbbo.github.io/coco-doc/C/#benchmarking, which doesn't mean to say that a non-default use case should not be included in the example experiment code comments.

When an upcoming workshop is on the horizon, the latest setting is probably the most common use case, hence we have always used this as default. Then, as so often with code duplication, it becomes rather a burden that this change would need to be made in each and every example experiment implementation, instead of just once in the suite itself. The other way around, it seem also rather undesirable that intended default changes in the suite do not propagate to the example experiments automatically.

**Comment by brockho** [comment]
Summary of the discussion from December 8, 2016: 
* the `year` option should go out of the example experiment,
* a better documentation (or a link to it) should be close to the experiment code
* the latest instances should become default in the test suites (as implemented in `C`)

**Comment by nikohansen** [comment]
I think the `dimension` option should also go, such that just the suite and observer name(s) need to be changed to get it running on a different testbed.

**Comment by brockho** [comment]
Outcome of the discussion on Jan 12, 2017:
- default experiment should be on `bbob` for all languages
- we have a map from all suite names to the observers in `coco_suite.c` such that the example experiment can call the observer with the same name than the suite

**Comment by brockho** [comment]
This issue can be closed, now that the items from the last entry above are solved with the latest commit in the `feature-refalg` branch.
