### ISSUE TITLE
_extracted_ folders should be ignored

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1251]
When using `python -m cocopp path_to_some_data/*`, it apparently happens that the data appear twice in the figures. 

<img width="404" alt="screen shot 2016-12-09 at 20 04 04" src="https://cloud.githubusercontent.com/assets/7316439/21061150/6ad8a192-be4b-11e6-9510-fc362b2ec8c5.png">

The reason seems to be the data found in the `_extracted_...` folders to which the zip data have been previously extracted to. These folders must be ignored, or deleted after usage. The reason why they are currently not deleted is to reduce waiting time.

**Comment by brockho** [comment]
A remark after discussing with @dtusar: it might be better to check whether the corresponding zip file to a used `_extracted_...` folder is among the arguments to the postprocessing (and only use the original one) instead of immediately ignoring all `_extracted_...` folders. This will allow to prevent the above from happening but also supports a user who want to use an `_extracted_...` folder if performance is an issue.

**Comment by nikohansen** [comment]
I am very much against supporting the interface to use an `_extracted_...` folder directly when the original zip file is not an argument. Users can unzip the data themselves beforehand, if they want to address the mentioned performance bottleneck. If we want the unzipped folder to remain available to the user, we should use a different name than `_extracted_...`.

**Comment by dtusar** [comment]
The extraction folder is now `.extracted_...`. Can we close this issue or is there anything else we should change?

**Comment by nikohansen** [comment]
We could think of removing the `_extracted_...` folders and of checking the arguments for the pattern `?extracted_*` and giving it some light error handling. Not too important though.

**Comment by dtusar** [comment]
Okay, I will close the issue then.
