### ISSUE TITLE
Octave crashes with new LS code

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1298]
The `python do.py run-octave` crashes regularly on the linux CI slave:
```
[...]
   COCO TIMING: dimension 10 finished in 1.276746e-04 seconds/evaluation
   COCO TIMING: dimension 20 finished in 1.213737e-04 seconds/evaluation
   COCO TIMING: dimension 40 finished in 1.280396e-04 seconds/evaluation
panic: Segmentation fault -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
```
After a bit of investigation (the problem also crashes on my Windows laptop), I narrowed it down the error in the sense that the segmentation fault only appears when the `cocoSuiteFree(suite);` is called in the end of the `exampleexperiment.m`. If I take it out, the code runs cleanly. Commenting (in) the `cocoObserverFree(observer);` does not have any effect. Hence, it is likely that a change in the `bbob` observer during the extension towards large-scale problems causes this error.

**Comment by oaelhara** [comment]
It might be coming from the 
`/**
 * @brief frees the data of bbob observer
 */
static void observer_bbob_data_free(void *data){
  /*coco_free_memory(((observer_bbob_data_t *)data)->dimensions_in_current_info_file);*/
  (void) data; /* to silence warning*/
}`

A possible solution would be to simply not use a free function since for now, it's just a place-holder
; thus replacing in `observer_bbob.c`:
`observer->data_free_function = observer_bbob_data_free;`
by 
`observer->data_free_function = NULL;`

**Comment by kostasvar** [comment]
When running `python do.py run-octave` at my laptop (macOS) , there is no segmentation fault.

**Comment by nikohansen** [comment]
same here, on macOS it works (`development` and `devel-LS` branches)

**Comment by kostasvar** [comment]
Running `python do.py run-octave` in two of the lab machines (CentOS) and a virtual machine with Ubuntu, there was no segmentation fault.

**Comment by brockho** [comment]
Seemingly, the latest bug fixes (in the `mixint` branch of @ttusar) have solved these problems. Also on my windows machine, the error does not appear anymore (neither on the `bbob` nor on the `bbob-largescale` suite).

I would therefore consider this issue to be solved.
