### ISSUE TITLE
"bi-objective data will be made available online in the next days"

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#1300]
said in 
http://coco.gforge.inria.fr/presentation-archive/2016-GECCO/11_Anne_bbob-2016-wrap-up.pdf
Any reason for keeping the data private?

**Comment by brockho** [comment]
No data will be kept private with COCO. The only reason for not providing the data yet is that it took us longer than expected to make COCO handle new test suites and to provide consistent plots even when the hypervolume reference values change over time. Since we do not want to have inconsistent data available that might result in papers with inconsistent and confusing information and thus might be misinterpreted easily, we will wait with providing them until the release 2.0 is out.

**Comment by loshchil** [comment]
Thanks for the reply! The text "in the next days" just sounded like there are no technical issues to make the data available.
