### ISSUE TITLE
scaling plots with number of constraints

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1369]
It seems not easy to see the scaling of the aRT with the number of constraints from the current plots. We should therefore think about having a plot with the number of constraints on the x-axis and the aRT on the y-axis (for one target and all dimensions). For the former, we should use the actual numbers, e.g. `1,2,3,10` in `2-D` or `1,2,5,9,10,11` in `10-D` and aggregate over all problem instances we have for this specific number of constraints (e.g. 15*3 instances for 1 constraint in `2-D` because also `n/2` and `n-1` equals `1`). 

It seems to make sense to start with plots for a single algorithm and one target and if this looks useful to provide the same for more algorithms (and only one dimension per plot).

**Comment by asmaatamna** [comment]
How to do it: (@nikohansen from skype conversation): "I would copy ppfigs.py to a new file and go from there, in particular line 459 dictFunc[f][alg].dictByDim() need to do this by number of constraints instead of by dimension. I don't know how the number of constraints is represented in the DataSet list, it might be difficult to access. There might be easier ways, but I currently don't see them."

**Comment by nikohansen** [comment]
```python
suite = Suite('bbob-constrainted', '', '')
nb_constraints = suite.get_problem_by_function_dimension_instance(1, 5, 0).number_of_constraints
```
should work to get the number of constraints.

**Comment by paulduf** [comment]
I close this one as it's been done for the release (see also [this PR](https://github.com/numbbo/coco/pull/2068)).
