### ISSUE TITLE
Equal width of plots

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1394]
Choosing the names of the algorithms in the way we do it now produces plots of different widths which is annoying in the html output. Moreover, the names can be too long at the moment in the sense that the names can dominate what we see in the plot such that data is only displayed in <50% of the space.

**Comment by nikohansen** [comment]
To ensure constant width, it is probably sufficient to use the right clipping option when saving the figure with `matplotlib`.

**Comment by brockho** [comment]
Problems also occur at the moment with the scatter plots due to too long function names:

![image](https://user-images.githubusercontent.com/13706996/27611097-2f8297ae-5b91-11e7-9f0f-08399209ab66.png)

**Comment by islandblue** [comment]
The length of the algorithm name has no direct bearing on box width. It affects box height, causing it to increase, so it has to be scaled down to fit. Scaling down is done on both dimensions, though, so plot ends up losing height and width. Playing with parameters might help prevent width loss, but the real problem here is height. Clipping is not a solution, either. It would be equally annoying to see clipped axis labels.

I'd recommend either decreasing the font size, abbreviating algorithm names or wrapping the y-axis label.

**Comment by nikohansen** [comment]
This issue should be solved already with the changes from commit https://github.com/numbbo/coco/commit/5b6ddcb31336826ad7af8e7372554c892740fab0

**Comment by nikohansen** [comment]
Assuming this has been solved, if not please reopen.

**Comment by nikohansen** [comment]
There remains a small issue, if the number of evaluations exceeds 1e10, due to the y-label annotation: 
<img width="574" alt="screen shot 2017-09-06 at 16 44 49" src="https://user-images.githubusercontent.com/7316439/30118388-324b60dc-9323-11e7-93ce-49d6513ff1ca.png">

**Comment by islandblue** [comment]
Yes, but then the issue is no longer unequal widths, right? We want them aligned as well?

**Comment by nikohansen** [comment]
They would be aligned if they would have the same width (of course all depends on which width we are talking about).

I wouldn't consider this important for the time being (1e10 evaluations doesn't happen too often anyways and the looks aren't very much disturbed), in particular not before #1530 is not solved.

**Comment by nikohansen** [comment]
Fill be fixed together with #1530
