### ISSUE TITLE
Continuous Integration platform

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1463]
Thanks to @FloopCZ we now have another CI coupling here

https://circleci.com/gh/numbbo/coco

using the `.circleci/config.yml` configuration file, see also #1462. 

The big advantage of [circleci](https://circleci.com) over Jenkins seems to be simplicity, while I am not sure that Windows is available for testing. We now should explore and consider whether we may want to abandon Jenkins or use [Travis](https://travis-ci.org/) as another alternative.

**Comment by FloopCZ** [comment]
@nikohansen Not CircleCI neither Travis support Windows. They both provide basically the same service, but at the moment, CircleCI is a lot more configurable since you can choose your own docker image. That is the reason why I suggested CircleCI.

If you want CI for Windows, I suggest [AppVeyor](https://www.appveyor.com/) which is again free for open-source projects. Both CircleCI and AppVeyor can work seamlessly side by side. However, I have basically no experience configuring Windows CI. How do you even build the coco on Windows? Are you using MSVC or GCC? Maybe if you provide a list of commands that performs the same operations as the `.circleci/config.yml` on Linux, I will be able to make a simple config for AppVeyor as well.

**Comment by FloopCZ** [comment]
@nikohansen Because there is no better way to spend a Sunday morning, I have set up the AppVeyor config for you in #1462. :-) So if you register numbbo/coco in the [AppVeyor](https://www.appveyor.com/) website and merge the PR, it should work out-of-the-box. Both Python 2 and Python 3 are tested, just cusomize `appveyor.yml` to suit your needs.

Go to the appveyor website, login using your GitHub account and in the GitHub login popup window, grant access to the numbbo group. Then press Add Project and select coco.

**Comment by nikohansen** [comment]
Nice, though I now get the following error message `Specify a project or solution file. The directory does not contain a project or solution file.`

**Comment by FloopCZ** [comment]
@nikohansen It should go away when the PR is merged and it will see the appveyor.yml file.

**Comment by FloopCZ** [comment]
I believe that docker-based solutions (e.g., CircleCI) are better than pure Jenkins. You can, for instance, create a new branch with a dependency to a new library, you simply mention the dependency in the `.circleci/config.yml` and your branch is automatically tested without having to reconfigure some Jenkins environment on some remote server (the same stands for pull requests as well). You can also be sure that you have not forgotten any dependency, since your build always runs in a clean environment only with the packages you have explicitly installed. Furthermore, you can easily test your project on a new OS version by simply replacing the image version.

Also the GitHub integration of those services seems to be better and simpler. On the other hand, Jenkins is useful if you have a private project and don't want to pay for an extra CI service, or if you have a huge project requiring a lot of resources to be build. I would, however, still use docker inside Jenkins instead of a pure Jenkins.
