### ISSUE TITLE
Python 3 branch

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1465]
We should ASAP merge the Python 3 branch https://github.com/numbbo/coco/tree/devel-python3 back into the development branch or accept https://github.com/numbbo/coco/pull/1462. Can anyone confirm that the output _in Python 2_ is the same as for the development branch?

**Comment by islandblue** [comment]
I think I can confirm with almost full certainty by visual inspection.

I'll have the script for a more thorough comparison ready tomorrow at the latest. It needs to be run on the post-processing results of multiple algorithms, just to be complete.

The investigation revealed a few peculiarities we are looking into right now, but none of it seems to be the result of the changes in the devel-python3 branch. In any case, I'd say we would prefer to keep the changes in devel-python3, since they saved us a bigger lot of work with auto-conversion, and work through any potential minor bugs that might appear later anyway.

I'll update as more concrete confirmation becomes available, but feel free to merge the branches depending on urgency if this much certainty is satisfactory.

**Comment by nikohansen** [comment]
I am probably missing something, but I don't see the advantage to keep a separate `devel-python3` branch unless the branch is regarded to be unstable. Python 3 support should not break the Python 2 functionality. Automatic conversion should not break due to changes in the development branch.

**Comment by islandblue** [comment]
The comparison script is run and the outputs of the development branch and the devel-python3 branch are compared. The summary result is that none of the 120 svg files in the post-processing output are identical. The graphs 'look' the same, but there are differences in the svg files that look nontrivial. Far be it from me to parse an svg file just by looking at its text, so I suppose we should discuss the next step at this point. I'm attaching the comparison script and the diff log.
[diff results.zip](https://github.com/numbbo/coco/files/1180398/diff.results.zip)

**Comment by nikohansen** [comment]
The branch has been merged, so I close this issue, see #20 for the general point be compatible to Python 3.
