### ISSUE TITLE
Issue a warning with multiple comments in archive merging

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1471]
For some reason, the archive merging between BBOB-2016 and now resulted in (incorrect) archive files that have multiple times the same instance comments in them. Unfortunately, this causes some errors with the current archiving code as it assumes the normal file format (i.e. only two lines of comments in the very beginning) and seems to stops reading in of data after the second block of comments.

Whether there are more data blocks of which only one is handled should at least be checked and the preprocessing shall issue a corresponding warning (or even an error) when it detects a second block of comments. The easiest seems to me to not care at all about the comments and assume that all data within the same file belong to the same function/instance/dimension combination as indicated in the filename (and as written by the current `bbob-biobj` logger.

**Comment by nikohansen** [comment]
Do we have a data format specification?

**Comment by ttusar** [comment]
@brockho Can you upload somewhere (or send me) one file with these multiplied instance comments?

**Comment by ttusar** [comment]
> Do we have a data format specification?

We do. The archive files are supposed to be named either 
`[suite-name]_f[function]_i[instance]_d[dimension]_*.*` or 
`[suite-name]_f[function]_d[dimension]_*.*`. 
In the first case, we expect to have only one problem instance and the instance number is read from the file name. In the second case, one or more different problem instances are expected and the instance numbers are read from the file. In this second case, all solutions following the line  
````
% instance = NUM 
````
belong to instance NUM - up to the end of file or the next comment line containing an instance number. 

The biobjective logger has long been producing archives only in the first format (one file for each problem instance), but we still have some older archive files lying around and the code supports (and documents) both formats. 

The problem encountered by @brockho was that his `adat` file had consecutive "instance lines" without any solutions in between
````
% instance = NUM 
% instance = NUM 
````
As he correctly assumed, the algorithm stopped after it encountered the second instance thinking it had already read in all the solutions for instances NUM. Now this is changed in the following way:
- For the first format we expect that all solutions in the file correspond to the instance given in the file name and all comments are simply skipped. 
- For the second format, we keep track of how many solutions were given for each instance. If an instance has no solutions, an exception is raised. I could change it to a warning, but since this should never happen in a normal case, I think an exception is more appropriate. 

I have the code ready to be pushed, but I'll wait for the critical issue to be fixed. If you want me to change anything, let me know.

**Comment by nikohansen** [comment]
This may be related to #1108, also loosely related to #745.

**Comment by ttusar** [comment]
It shouldn't be related to any of them, because this issue affects only `adat` files, which are never used in post-processing.
