### ISSUE TITLE
No scatter plots with 2nd cocopp.main call

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1499]
When calling `cocopp.main` twice with two algorithms, COCO does not produce the scatter plots in the second run (nor the plots behind the link "Runtime distribution for selected targets and f-distributions" but this is of less importance). Single-function and aggregated ECDFs, tables, and scaling graphs are produced as expected.

**Comment by nikohansen** [comment]
Weird, but the reason seems to be rather simple. For example, `genericsettings.isScatter` is set to `True` on import, _and only on import_. Then it might be set to `False` depending on the calls and will never be `True` again by normal execution. The logic doesn't seem right, but the passing of the input options into the setting may in general deserve a full revision.

**Comment by nikohansen** [comment]
A simple way to address the problem is to type
```
cocopp.genericsettings.isScatter = True
```
before to call `cocopp.main` again. 

In general if `cocopp.main` would do this by default we could not be able anymore set the option to `False` from the Python shell. It seems quite desirable to be able to control `main` not only from the input args when called from the Python shell. 

I don't see an obvious good solution to these two requirements (control vs no hidden changes of the default), as restoring the original setting may also lead to confusion later on. As a provisional measure my idea is to implement a message which outputs the changed setting when `cocopp.main` was called.

**Comment by brockho** [comment]
Really weird. `cocopp.genericsettings.isScatter` is always `True` for me, right before and right after the second call. But no scatter plots.

I did not look much into the code yet, but `cocopp.genericsettings.isScatter` cannot be the reason: I did not find any place where it is set to `False` except when the input arguments are checked and together with the above observation, the bug has to be caused by something else (to be investigated further).

**Comment by nikohansen** [comment]
Now `rungeneric` prints all `genericsettings` that are different from the original setting. That could help to further investigate this problem.

**Comment by dtusar** [comment]
The main reason for this behavior is the list of `foreground_algoritms`. This should be solved with #1507. 

If you add specific parameters (like `--tab-only`) when calling main() you can still change the value of `genericsettings.isScatter` to `False`. I made a small change so that the mentioned parameters have the desired effect in the current run but do not change the value of `genericsettings.isScatter`.

**Comment by brockho** [comment]
Okay, I will check later whether #1507 solves this. Just for the record: I did not set anything of `--tab-only`, I just called `cocopp.main` twice from within the IPython shell.

**Comment by brockho** [comment]
Since the current code in the development branch (with #1507 in particular) does not show this issue anymore, I am closing it.
