### ISSUE TITLE
Test-preprocessing fails

### ISSUE THREAD

**Issue by dtusar** [numbbo/coco#1544]
On Thursday I changed back the package installation location (in `do.py`) to system space. Since then the test-preprocessing (nightly build) fails due to permission rights.

**Comment by brockho** [comment]
I tried to change the permissions of the corresponding folder and the installation works now. However, I also de-installed all coco-related modules to check what is going on and I now get a `cocopp not installed error` with `test-preprocessing`:
```
test_reconstruction.py:137: in run_merge_lines
    from merge_lines_in_info_files import merge_lines_in
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    from __future__ import absolute_import, division, print_function, unicode_literals
    try: range = xrange  # let range always be an iterator
    except NameError: pass
    import numpy as np  # "pip install numpy" installs numpy
    import sys
    import shutil

>   import cocopp
E   ImportError: No module named cocopp

merge_lines_in_info_files.py:25: ImportError
```

It seems as if `do.py` is not installing the `cocopp` module before to test the preprocessing. This should be changed - otherwise, the test always runs with an outdated version of `cocopp` if it already exists.

**Comment by brockho** [comment]
Missed to close this one for a long time.
