### ISSUE TITLE
data archive filenames

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1580]
I found these names:
```
['bbob/2015-GECCO/BSif.tgz'],
['bbob/2015-GECCO/BSifeg.tgz'],
['bbob/2015-GECCO/BSqi.tgz'],
['bbob/2015-GECCO/BSrr.tgz'],
['bbob/2015-GECCO/Sif.tgz'],
['bbob/2015-GECCO/Sifeg.tgz'],
['bbob/2015-GECCO/Srr.tgz'],
```
in our data archive at `http://coco.gforge.inria.fr/data-archive`.
_Given the implicit naming conventions we have used over many years_, these names are IMHO unacceptable and _must_ change. A name cannot just give no indication whatsoever what is in the data set (given all other names do). Using the algorithm name and author has proven to be useful, but we can also try to come up with even more useful conventions.

On that note, `2017-outsideGECCO/` is not a nice folder name either and inconsistent vs `2017/` and `2015-GECCO/` (the latter is inconsistent with most others). How about `2017-no-workshop` and `2015`?

Rationale: There are only disadvantages to have cryptic filenames. Besides that informative filenames are useful for simple browsing, we are likely use the filename to search for entries of interest for some time to come, because it is rather tedious to actually implement different ways and start the maintenance for 150+ data sets.

**Comment by brockho** [comment]
The filenames should be all updated right now, hopefully consistent with the previous (implicit) naming convention(s). What is still missing is detailed in #69 such that I suggest to close this issue here.

Related to the names of the folders: `2017-outsideGECCO` is now renamed to `2017-others`, consistent with `2014-others`. I suggest to keep `2015-GECCO` because it is more consistent with `2015-CEC` than a simple `2015` would be plus, the ordering will be different than what we have right now (and how it was historically: CEC happened before GECCO), because `2015-CEC` would come after `2015` if I am not mistaken.

**Comment by nikohansen** [comment]
I am in favor of globally  consist names, hence I am not sure about a single exception from the year-only rule as name for the GECCO entries. It would be different if the rule changed from a certain year on, in order to keep backwards compatibility and have a rule more adapted to the future. 

I currently don't see a problem with changing order for the `2015` entries. It is not even likely that it would break any of the current tests and if it would it would be easy to fix.

**Comment by brockho** [comment]
Can be closed.
