### ISSUE TITLE
improving behavior on hash checksum fail in DataArchive

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1596]
Currently a `ValueError` is raised when the hash checksum test fails. Preferably, after a warning is issued, another download should be tried.

**Comment by brockho** [comment]
I am not sure that here is the right location to report my issue (I can also open a new one later on if this seems better):

I realized that I had to correct a data file (concretely `bbob/2017/DTS-CMA-ES.tgz`) because the online available file was incorrect. After the change in the file, however, `cocopp.bbob.get('DTS-CMA-ES.tgz)` did not download the new file and I had to delete the file in my `.cocopp` folder by hand to make this happen. The next call to `cocopp.bbob.get('DTS-CMA-ES.tgz')` then downloaded the file with, of course, complaining about the wrong checksum.

Was the mistake on my side, in the sense that I should correct the checksum in `findfiles.py` myself and everything is supposed to work well, or is this a more general problem?

**Comment by nikohansen** [comment]
You have to either remove the existing checksum or (I guess preferably) to replace it with the new checksum in the code. This seems IMHO to be the right way to handle file changes. They should not happen all too often anyways.

There is a procedure to write a definition file and I believe the file can be passed as argument to the `COCODataArchive.__init__` method. Though the does not help with the existing "official" data.

**Comment by brockho** [comment]
I am not sure how I am supposed to compute the checksums myself. I tried
```
cocopp.findfiles.COCODataArchive()._generate_names_list(filename='archive.txt')
```
but I get this error:
```sh
IOError                                   Traceback (most recent call last)
<ipython-input-107-71c290cefaa6> in <module>()
----> 1 cocopp.findfiles.COCODataArchive()._generate_names_list(filename='archive.txt')

c:\users\dimo\anaconda2\lib\site-packages\cocopp-2.0.700-py2.7.egg\cocopp\findfiles.pyc in _generate
_names_list(self, filename)
    752                          os.path.getsize(path) // 1000)] # or os.stat(path).st_size
    753         if filename:
--> 754             with open(os.path.join(self.local_data_path, filename), 'rt') as file_:
    755                 file_.write(repr(res))
    756         return res

IOError: [Errno 2] No such file or directory: 'C:\\Users\\dimo\\.cocopp\\data-archive\\archive.txt'
```
Creating an empty file `archive.txt`, I get then
```
IOError                                   Traceback (most recent call last)
<ipython-input-111-a1eae60c41e5> in <module>()
----> 1 mcda._generate_names_list('archive.txt')

c:\users\dimo\anaconda2\lib\site-packages\cocopp-2.0.700-py2.7.egg\cocopp\findfiles.pyc in _generate
_names_list(self, filename)
    753         if filename:
    754             with open(os.path.join(self.local_data_path, filename), 'rt') as file_:
--> 755                 file_.write(repr(res))
    756         return res
    757

IOError: File not open for writing
```

What do I do wrong? [I use Windows with Anaconda python 2.7]

**Comment by brockho** [comment]
Sorry, I found it now myself (by just scrolling further down in `findfiles.py` :-) ): The checksum is computed via the `_hash` method.

**Comment by nikohansen** [comment]
`cocopp.findfiles.COCODataArchive()._generate_names_list` didn't interpret the input argument correctly. It's still in early alpha stage.

**Comment by nikohansen** [comment]
Code has been largely revised and will be pushed in the coming days.
