### ISSUE TITLE
development branch CI test went from green to red

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1646]
without that the branch actually changed. [The error](https://ci.inria.fr/numbbo/job/Coco-devel-linux/dotype=test-postprocessing,label=numbbo-ubuntu-12p04-i386,pyversion=python/966/console) is related to latex compilation.
```
+ python do.py test-postprocessing
EXPAND	code-postprocessing/setup.py.in to code-postprocessing/setup.py
PYTHON	setup.py install in code-postprocessing
PYTHON	test.py in code-postprocessing/cocopp
ERROR: return value=1
Input file or folder ./BFGS_ros_noiseless could not be found.
For help use -h or --help
Using grayscale settings.

Post-processing (1): will generate output data in folder ppdata/BFGS_ros_noiseless
  this might take several minutes.
Input file or folder ./BFGS_ros_noiseless could not be found.
LaTeX templates copied.
*** testing module cocopp ***
python -m  cocopp --no-svg --settings=grayscale BFGS_ros_noiseless
**  subtest 1 finished in  0.551265954971  seconds
Traceback (most recent call last):
  File "test.py", line 389, in <module>
    main(sys.argv[1:])
  File "test.py", line 223, in main
    run_latex_template("templateBBOBarticle.tex", run_all_tests)
  File "test.py", line 88, in run_latex_template
    assert not result, 'Test failed: error while generating pdf from %s.' % filename
AssertionError: Test failed: error while generating pdf from templateBBOBarticle.tex.
```

**Comment by brockho** [comment]
The problem turns out to be not properly installed/uninstalled cocoex/cocopp modules. Removing the eggs by hand solved the problem on the linux slave. I'll take care of the rest later.

**Comment by brockho** [comment]
The latest error (now with the `master` branch) was caused by only partly downloads of the data. Files with the right names have been written but the sizes have been in the range of 20-30KB only, causing the subsequent tests to not download anything anew. Removing the corrupted data solved the problem but another one surfaced that, finally, @nikohansen solved by cherry-picking another commit from the `development` branch.

After testing cleanly the `master` branch, the tests on `development` failed (as expected) and all four Jenkins slaves are cleaned up. Tests are running now and will hopefully run through again.

All tests ran through now and the `master` branch could be finally updated.

**Comment by nikohansen** [comment]
Looks like we back to green.
