### ISSUE TITLE
COCO functions' evaluations not incremented. (always get "zero" )

### ISSUE THREAD

**Issue by ncble** [numbbo/coco#1668]
COCO seems not working with multiprocessing.Process under Python. When I call a solver using multiprocessing, COCO will never count any evaluation of functions. Is that normal ? Please find the code (of solver) below to reproduce this error.
P.s I can upload my code that runs the solver if needed.

[Solver using multiprocessing]
```python
import numpy as np 
import multiprocessing
def random_solver(fun, x0, iter_num):
	n = len(x0)
	min_local = np.inf
	for _ in range(iter_num):
		newx = np.random.random(2)*10-5
		min_local = min(fun(newx),min_local)
		# print(fun.evaluations)

def random_multi_process(fun, x0, iter_num):
	proc = multiprocessing.Process(target=random_solver, args=[fun, x0, iter_num]) 
	proc.start()
```

**Comment by brockho** [comment]
Thanks for the error report.

Trying the code in an ipython shell (my jupyter notebook does not work at the moment :-( ), I get an
```
AttributeError: 'module' object has no attribute 'random_solver'
```
Can you therefore please send us also the full code that produces the error?

**Comment by brockho** [comment]
Together with @ncble, we looked at the code today and in the jupyter notebook (yeah, mine works again!) with
```
import cocoex
mysuite = cocoex.Suite("bbob", "", "")
fun = mysuite.get_problem_by_function_dimension_instance(1, 2, 5)
random_multi_process(fun, [0,0], 100)
print(fun.evaluations)
```
we get an output of `0` while with the unparallelized
```
import cocoex
mysuite = cocoex.Suite("bbob", "", "")
fun = mysuite.get_problem_by_function_dimension_instance(1, 2, 5)
random_solver(fun, [0,0], 100)
print(fun.evaluations)
```
we get `100` as expected.

Since COCO is not expected to work with parallel executions anyway (because the logger needs to get all function calls in a specific order on the same problem instance), we can close the issue (as a *won't fix*).
