### ISSUE TITLE
Curious marker placement and missing crosses in example experiment for beginners 

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1699]
If `example_experiment_for_beginners.py` is run as is, the following output is produced:

SVG
![slika](https://user-images.githubusercontent.com/13745935/34820638-6757a8c4-f6c1-11e7-947f-297aab490e71.png)

PDF
![slika](https://user-images.githubusercontent.com/13745935/34822346-eb56af4e-f6c6-11e7-8135-8c9ecdf7d11d.png)

Notice the missing crosses for 2-D and 3-D and the markers on the upper left corner (only in the SVG plot).

**Comment by brockho** [comment]
The markers in the upper left corner are artifacts that we have seen already before (unfortunately I cannot find the corresponding issue/discussion at the moment). If I remember correctly, they come from a quick fix that we did when either numpy or matplotlib changed its behavior. Why they show up in one format but not in the other is not immediately clear to me, but its probably also related to python behavior outside of COCO.

The missing crosses for 2- and 3-D seem to be the correct behavior as "The cross on the ECDF plots of COCO represents the median of the maximal length of the unsuccessful runs to solve the problems aggregated within the ECDF.". Since the 2- and 3-D plots go up to 1, all runs are actually successful and no cross can be/is displayed.

**Comment by nikohansen** [comment]
The reason why we see the markers in the upper left corner only in one format could be a different background color, transparent vs white.

**Comment by brockho** [comment]
By solving #1670 and #1700 respectively, this issue should solve automatically. Hence, we decided today to close it.
