### ISSUE TITLE
budget setting for postprocessing

### ISSUE THREAD

**Issue by AmerDraa** [numbbo/coco#1711]
Hello everyone, 

Is there any means to choose a specific budget for post-processing of data for BBoB test-bed?

As you know, some algorithms use 10e+5 function evaluations, while others use 10e+4 evaluations; besides, a fair comparison would be well established only if the compared algorithms used the same budget.

I restate the request: is it possible to consider, when postprocessing, only the 10e+4 first evaluations for the data of algorithms run for 10e+5 function evaluations?   

I do really need to do many comparisons, with a medium budget of 10e+4 evaluations, of my algorithm against those algorithms whose data is available at: http://coco.gforge.inria.fr/doku.php?id=algorithms-bbob .

Thank you in advance.

**Comment by nikohansen** [comment]
Hello @AmerDraa , it is not possible to choose a specific budget in the post-processing, because it is not necessary. The comparison is fair even when the budgets differ widely. _The comparison is always valid (only) up to the smallest budget between the compared algorithms._

Specifically, results up to the budget value are (almost) exactly the same irrespectively of how much longer the algorithm has been run. The results may be slightly more accurate for the algorithm which has been run with a larger budget.

**Comment by AmerDraa** [comment]
Dear nikohansen,

Thank you so much for the clear answer, I do appreciate the clarification you have provided.

All the best.
