### ISSUE TITLE
Lines to the algorithms names are missing in the ECDF plots

### ISSUE THREAD

**Issue by dtusar** [numbbo/coco#1724]
Example:

![example](https://user-images.githubusercontent.com/13744819/37036205-32649b28-214f-11e8-83db-3a281140fa6a.png)

**Comment by islandblue** [comment]
Commenting out the following line

https://github.com/numbbo/coco/blob/bf0fb72cd081e003d4167e6ef1b59b35975278ae/code-postprocessing/cocopp/ppfig.py#L566

brings the lines back, so apparently the third plot command in `plotUnifLogXMarkers()` is not just to display the label, but also the line leading to it.

It is clear that the coordinates for this line are supplied after `plotUnifLogXMarkers()` returns, but I couldn't find it easily, since there are numerous ways this could have been coded.

The immediate conclusion is, setting `linestyle = ' '` and passing `0., 0.` for coordinates no longer qualifies as a workaround to `matplotlib`'s `nan` problem (issue #1708).

Another frustrating observation is that the merge to `development`, which made its way to `master` as well, doesn't include the `nan` fix in the first place.

https://github.com/numbbo/coco/blob/bf0fb72cd081e003d4167e6ef1b59b35975278ae/code-postprocessing/cocopp/ppfig.py#L568

So for the moment, unless we can track down where the coordinates are supplied to the third plot, we need to refrain from setting `linestyle = ' '`, and we cannot keep `nan` coordinates either. I will keep this line visible and see how the output looks like, Maybe the third line was meant to be visible in all graphs. Then we never had to supply `[ ]` or `[np.nan]` in the first place, any number would have been fine, since it would be overwritten later anyway. If not, the only other option I can think of to keep it out of sight is to plot a single point to somewhere invisible, like `[-1], [-1]` or something, hoping that won't break something else.

**Comment by islandblue** [comment]
@dtusar, can you run the code in the `islandblue-issue1724` branch on your data and have a look at the output? I couldn't see a problem in my results.

**Comment by islandblue** [comment]
Regarding the readability of legends, the only working solution at present is to plot a span under the legend and make sure the legend stays on top of the span. Apparently, the implementation of layering in `matplotlib` leaves something to be desired, though. I took the advice in [this issue](https://github.com/matplotlib/matplotlib/issues/5045) and played with z-orders for a bit until I was able to get the following graph.

![issue1724](https://user-images.githubusercontent.com/27438398/37294872-18671544-2617-11e8-94d7-db05cb8bdb9e.png)

Lacking specs, I need your opinion @brockho, @nikohansen whether this fulfills the expectations. The modified code is in [`islandblue-issue1724`](https://github.com/numbbo/coco/tree/islandblue-issue1724) branch. If you approve, I will create the pull request.

**Comment by brockho** [comment]
Thanks @islandblue. The plot looks okay to me. The question that remains is whether the points for the longest run of the artificially restarted algorithm is visible if larger than `1e7` times dimension. To answer this, we first have to find a data set that shows these points to the right of the `1e7n` line. We should discuss tomorrow and then do a release very soon, because people keep reporting the issue.

**Comment by islandblue** [comment]
The fix is merged to `development` branch. The problem should be solved on the `master` branch as soon as we merge `development` into `master` to amend the release. Until then, the issue can stay open as a reminder.
