### ISSUE TITLE
Choice of the region of interest in the (mixed-integer) multiobjective case

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1793]
The next step towards answering this question is to see whether the solutions in our Pareto set approximations, we know are lying outside of `[-5,5]^n`, are actually non-dominated (are they close to the Pareto set?).

We can do this by optimizing (e.g. with CMA-ES) the COCO hypervolume with the Pareto set approximation's solution as reference point.

**Comment by ttusar** [comment]
As per today's discussion, we should set the ROI of the continuous variables for the mixed-integer bi-objective suite to `[-5, 5]^n`.

**Comment by nikohansen** [comment]
Isn't that a little bit too optimistic that we can go from `[-100,100]` right back to `[-5,5]`?

**Comment by ttusar** [comment]
I believe the reasoning was that since the smallest problem dimension is 5, this should be reasonably safe to do...

**Comment by nikohansen** [comment]
Yes, I also understand that with integers there is less of a chance to get good solutions outside the bounds, because integers themselves cannot take values outside the bounds at all. Yet, I don't see the reasoning how/why `[-5,5]` is now "safe" in >=5-D knowing that before it was set to `[-100,100]` to make it safe in 2-D.

**Comment by nikohansen** [comment]
Currently, the `lower_bounds` and `upper_bounds` property of a `cocoex.interface.Problem` is set to -100 and 100 for continuous variables.

**Comment by brockho** [comment]
Looks like, we can close the issue then.
