### ISSUE TITLE
A recipe for running experiments with different dimensions

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1968]
Re. https://github.com/numbbo/coco/issues/1966#issuecomment-629847985

Shall we have a recipe for this, one that is not deeply buried in a soon-to-be-closed issue?

It could go into the [howto folder](https://github.com/numbbo/coco/tree/master/howtos), I guess basically a copy-paste of the above linked comment?

@ttusar ?

**Comment by ttusar** [comment]
See https://github.com/numbbo/coco/pull/1969 

I think you would probably be able to add some more useful information under the "disclaimer" part (such as that if dimensions go over some number, one would be better off using the large-scale suite instead of the bbob - at least I imagine this would be the way to go...)

**Comment by ttusar** [comment]
It's now available on the development branch.
