### ISSUE TITLE
Are instances from the constrained testbed uniform?

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2053]
Should we use/allow simulated restarts for the constrained testbed instances?

The relevant variable is `cocopp.testbedsettings.CONSBBOBTestbed.instances_are_uniform`.
For development purposes, the setting can be directly assigned/changed before to run the post-processing.

**Comment by nikohansen** [comment]
@paulduf , could you comment on this?

**Comment by paulduf** [comment]
I'm not very familiar with the simulated restarts but here is my point of view. So we know/have proof that the hypothesis of uniform instances is valid for the (function, dimension) pairs of the BBOB testbed.

Starting from the definition of a problem instance, that is, a quintuple "search space dimension, function, instantiation parameters, quality indicator mapping, and quality indicator target value", can we find a reason why we don't construct uniform instances for the constrained testbed. In the unconstrained case, the "instantiation parameters" are the shift in the search space, the shift in the optimal value, and the rotation, if any. The first thing I can think about in the constrained case is the volume of the feasible space, which varies among different instances, as shown by the data. To me the reason is that the constraints generation also depends on the seed and the instance, and this additional instantiation parameters may violate the hypothesis of uniform instances. Or can we have a proof, at least a feeling, that this does not impeach to "different instances as random repetitions that could arise, for example, by restarting from different initial solutions on the same instance" ?

**Comment by nikohansen** [comment]
FTR, code-wise, the current default is

```python
class TestBed:
    instances_are_uniform = True
```
and
```python
class CONSBBOBTestbed
```
does not overwrite this, AFAICS. It is only overwritten for the biobjective suites where a simulated restart also can not use the already obtained non-dominated archive from the previous runs.

**Comment by paulduf** [comment]
I remember I did remove this when working on the postprocessing but maybe not at the right place and somehow it was lost, so we can do as you suggest and overwrite this at the class level ?

**Comment by nikohansen** [comment]
I currently don't see a particularly good reason to disable it.

**Comment by paulduf** [comment]
We checked some numerical results and came to the conclusion the random effects across different sets of instances are fine, so simulated restarts stays enabled when post-processing data with constraints..
