### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by sam1mitchell1-hub** [numbbo/coco#2093]
I have been trying to run solvers on some of the the problems from the bbob-biobj suite in parallel using the multiprocessing python package. 

So I have tried to tackle the issue in a slightly different way. (Hence the edits of this post)

I am now having issues with an attribute error: Can't pickle local object "main.< locals >.function_name'"

If anyone knows how to solve this issue I would greatly appreciate it.

**Comment by paulduf** [comment]
Hello,

It's hard to guess where the bug comes from without a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

Googling around, I can already find related errors [here](https://www.pythonpool.com/cant-pickle-local-object/) and [there](https://stackoverflow.com/questions/52265120/python-multiprocessing-pool-attributeerror) where the multiprocessing module is used.

Hence I am not sure this has anything to do with the `cocoex` module. If you can manage to come up with a simple code snippet (running one solver on one function is a good start) where this error happens, maybe I can further help you.

**Comment by brockho** [comment]
A minimal example code where you observe the issue is always helpful. In case you use the observer around the function to log data automatically (as in the `exampleexperiment2.py`): such a setup won't be parallelizeable as the same observer can only log a single function instance at a time. But parallelizing the entire benchmarking experiment (=1 algorithm run for every function, instance, and dimension combination of the test suite) is easy via the batches functionality, at least in python:

```
python exampleexperiment2.py  budget_multiplier=1e4 suite_name=bbob-biobj batch=1/17
```

for example, will split all problems of the `bbob-biobj` suite (more or less equally) into 17 batches and runs the first one of them for a budget of 1e4 times dimension many function evaluations. Then, `batch=2/17` runs the second batch etc. Benchmarking data from all those batches can be copied together into a single folder and postprocessed as if the data came from a single batch.

**Comment by sam1mitchell1-hub** [comment]
Thank you for your responses. Yes after further investigation, I believe it to be an issue with the multiprocessing module and not cocoex. I do apologise. 


I am running experiments that have required me to write some extra classes to wrap around problem instances. So I have made things a little more complicated for myself. Which I think is where the error comes from. I have also written an equivalent of the exampleexperiment2.py that does a similar sweep through problems but does none of the post processing. 

I apologise again.
