### ISSUE TITLE
[DATA SUBMISSION] random search on the bbob-constrained test suite

### ISSUE THREAD

**Issue by paulduf** [numbbo/coco#2094]
Hello COCO developer!

Here is the random search data with a relatively large budget (2x10^5 times dimension (f+g) evals)

#### Reference and Description of the Algorithm
This data was generated from the `example_experiment2.py` script in the `cocoex` module using `cocoex.solvers.random_search`.
The batch implementation of random search has been recently modified to be compliant with the performance assessment in the constrained case in [this commit](https://github.com/numbbo/coco/commit/d2c9fe95da4bbc17dfa9cd8e99ccd3a8ac1533e0).
The previous implementation was querying first the objective for all sampled points in the batch, then all constaints, which caused trouble in the target triggering and undesirable plateaux in the ECDFs

#### Link to Data
The zipped file on google drive is roughly 40MB
https://drive.google.com/file/d/1RR7ywjaZUUAecKyNq5AKxmUdYeFrpc3b/view?usp=sharing

#### Optional: Source Code of Experiment
The source code is in the `cocoex` module.

**Comment by brockho** [comment]
Thanks, @paulduf, for the data submission. I could download the data from the provided link and will take care that it appears in the [official data archive](https://numbbo.github.io/data-archive/).

**Comment by brockho** [comment]
I don't know why it takes that long for the Github Pages to deploy, but the data is cleaned up and committed to the repository since Thursday: https://github.com/numbbo/data-archive/tree/gh-pages/data-archive/bbob-constrained/2022

I will leave this issue still here until the webpage shows up and until we can therefore access the data set directly in the postprocessing module (right now, the outdated archive definition file is loaded - as long as the webpage is not updated).
