### ISSUE TITLE
Clarifications: Continuous submissions, Parallel Runs

### ISSUE THREAD

**Issue by LazyLysistrata** [numbbo/coco#2199]
1. In a description of the Large Scale Test Suite, it is suggested to run experiments in parallel. There are several ways that I can imagine this could be done. Two examples:
(a) run each function on a separate processor/computer.
(b) run different instances of each function on separate processors/computers.
However, because of the way random numbers are generated in COCO, those ways will not always produce identical results.

Is there a preferred way that BBOBies recommend parallel runs be done?

2. Some entries in the BBOB data archive are described as "Continuous submission". 
What does "continuous" mean in that context?

**Comment by brockho** [comment]
Hi,

Many thanks for your detailed questions. Here a few (first?) comments:

ad 1) Since we only record the number of function evaluations until certain target precisions are hit, the way you parallelize the experiments does (should) not matter. The easiest is to distribute the 15 different instances over parallel runs (because you can easily instantiate the suite with the corresponding option and only get all functions/dimensions for a single instance id), but you can, in principle, run every specific function/instance/dimension combination on a separate computer. If you use python, this functionality is already implemented by calling something like `python example_experiment2.py budget_multiplier=1000 suite_name='bbob-biobj' batch=1/16` (this will run the first out of 16 parallel batches). When postprocessing, you just need to collect all folders from all batches into the same folder and postprocess this single folder.

The fact that the random numbers are not the same does not matter either because each run on a new instance is considered as an independent run. In principle, running the same stochastic algorithm on the same instance again or on a new instance is considered as an independent run. The reason for running once on each instance is to easily compare stochastic with deterministic solvers.

ad 2) Before 2020, all data submissions came (almost) exclusively from contributors to the BBOB workshops. Since 2020, we also allow data sets to be submitted at any (continuous) time and not only at a specific (discrete) time in the year. Those data sets are marked with "continuous submission" in the data archive tables.

**Comment by nikohansen** [comment]
> However, because of the way random numbers are generated in COCO, those ways will not always produce identical results.

I don't understand this sentence. With the possible exception of the (old) implementation of the noisy test suite, any problem instance is always the same on any computer, otherwise I would consider this to be a bug.

**Comment by LazyLysistrata** [comment]
There is nothing wrong with the problem instances. They, and the location of the minima, will be identical. However, running the functions in a different order (e.g. f1, f2, f3) will give different results for stochastic processes (e.g. running f3,f2,f1). The problem instances will be identical in all cases, however the number of function calls will most likely be different.

I use two different methods while developing codes which are hybrids of deterministic and stochastic. One method is perfectly reproducible, because I reset the seed to its original value for each function, dimension and set of instances. The other is (for want of a better term) "non-reproducible", because the sequence of random numbers will be different for each run. The problem instances are identical in both cases, so there is no bug for you to lose sleep over. :)

Sorry for the lack of clarity in my original question. I hope that I haven't muddied the waters further.
