### ISSUE TITLE
.dat file format in post-processing

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#394]
There is now an observer which writes additional lines (not triggered by hitting a target) in the `.dat` files. 

We must check the post-processing code that these lines are treated correctly. 

- they should not appear in the `evals` attribute of the `DataSet`. 
- they can and should be used to set attributes which normally depend in the `.tdat` files, namely the `funvals` attribute (I don't recall the details at the moment).

**Comment by dtusar** [comment]
The first item was fixed lat night. The second still needs to be implemented.

**Comment by dtusar** [comment]
Now the post-processing reads the data for funvals attribute from .dat files if the .tdat files don't exist. 

The code is not the same as for the .tdat files because in .tdat files we use all the lines, also the iterations that does not exist in all instances. In bi-objective case we use only the iterations that exist in all instances. If we are going to write only .dat files also for single objective case then the data from .tdat files will be slightly different than the data from .dat files.Just to be aware of that.

**Comment by nikohansen** [comment]
I believe that _all instances_ should include instances that reached the final target, does it?

**Comment by nikohansen** [comment]
See also #501

**Comment by dtusar** [comment]
This is not relevant any more since we have the .tdat files back.
