### ISSUE TITLE
Generate a pickled data set list of the artificial best 2009 algorithm

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#41]
```
The objective is that an artificial best algorithm data set list does not need 
to be handled any different than any other data set list and can be used as 
regular input argument to rungeneric. 

This is probably best done based on the algportfolio.py module. 

```

Original issue reported on code.google.com by `nikolaus...@gmail.com` on 15 Jun 2014 at 12:03

**Comment by brockho** [comment]
Besides bug #1170, the issue is partly solved within the `feature-refalg` branch which should go into `development` very soon. The `bestalgs` are now written as normal data sets on disk. Internally, however, `BestAlgSet` and `DataSet` are not too similar yet, in particular, `BestAlgSet` does not inherit from `DataSet`. Hence, we shall keep the issue open.

**Comment by brockho** [comment]
Finally, this latest issue of the release 2.0 milestone can be closed. All reference algorithms are updated now, `BestAlgSet` inherits from `DataSet`, and we even provide additional reference algorithms at http://coco.gforge.inria.fr/refalgs/ that did not make it into the Coco release directly. 

For looking at how the best-so-far reference algorithm evolved over time on the `bbob` and `bbob-noisy` test suites, we also provide now the corresponding data at the following two links:
http://coco.gforge.inria.fr/refalgs/bbob/ppdata-bbob-over-time/
and
http://coco.gforge.inria.fr/refalgs/bbob-noisy/ppdata-bbob-noisy-over-time/
