### ISSUE TITLE
no warning with unknown keyword

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#490]
```python
>>> suite = ex.Suite("bbob", "", "")
>>> len(suite)
2160
>>> suite = ex.Suite("bbob", "", "dimensions:10")
>>> len(suite)
360
>>> suite = ex.Suite("bbob", "", "dimension:10")
>>> len(suite)
2160
```
There should be a warning if the keyword does not match. Ideally, the warning tells me what the valid keywords are. 

Second, the naming convention is slightly inconsistent, because for `dimensions` it demands plural, for `instance_idx` singular. A solution could be to compare at most the first 8-or-something characters. Not too important though. 

From the Python working-in-a-shell perspective I would love to be able to find the documentation by, say, calling a function `coco_help_suite`. Just saying...

**Comment by nikohansen** [comment]
BTW, the same should be checked for the `observer`. To not know whether an option could have been silently ignored doesn't make debugging any easier.

**Comment by ttusar** [comment]
I agree, but the problem with `observer_options` is that they are being processed by different functions (the general observer and the specific observer that is being called), so it's not trivial to see which are ignored. Maybe it's best if the observer outputs the options that it read instead of those that it ignored... I will think about this and try to come up with a user-friendly solution.

**Comment by ttusar** [comment]
Would it be sufficient to produce INFO output listing all parameter values set through `suite_instances`, `suite_options` and `observer_options`?

**Comment by nikohansen** [comment]
It helps, but it still needs some effort to find out whether something went wrong. It's clear that a user will not do this each and every time. If you can list all values set, you can also compare this list to the input list? I know, this kind of stuff is (more than) a little annoying to do in C.

**Comment by ttusar** [comment]
The difficulty arises from the way the options are processed, or better said, from the fact that they are actually not processed :) The options string is only searched for each known option. This means it can contain many `key: value` pairs that have no meaning and everything will still work. 

The advantage of this approach is that is less sensible to formatting errors - if there is something wrong in one of the options, this does not affect the others. The disadvantage is of course that typos don't get caught. I don't think there is any other way to catch the typos than to process the input string. This might turn out to be quite challenging (or at least annoying) to do right - especially since we allow values with multiple words. But I can try if we agree it's important to do.

**Comment by nikohansen** [comment]
Here is a suggestion: count the colons found in the string and compare to the found keywords?

**Comment by ttusar** [comment]
I was thinking of something similar, yes. I'll try and see how it goes.

**Comment by ttusar** [comment]
This will still be a problem: 
> the problem with observer_options is that they are being processed by different functions (the general observer and the specific observer that is being called), so it's not trivial to see which are ignored

**Comment by nikohansen** [comment]
Functions that process options could/should return the number of found/processed keywords. Only if several functions can recognize the same keyword this wouldn't help.

**Comment by ttusar** [comment]
I have an idea that should work... I'll keep you posted.

**Comment by ttusar** [comment]
Ok, so now this works as follows. This code:
```C
  suite = coco_suite("bbob-biobj", "yeaR: 2016", "Dimensions: 2,3,5,10,20,40");
  observer = coco_observer("bbob-biobj", "Algorithm_name: RS ");
```
Produces these warnings:
````
COCO WARNING: coco_suite(): Some keys in suite instance were ignored:
 yeaR
Valid keys for suite instance are:
 year
 instances

COCO WARNING: coco_suite(): Some keys in suite options were ignored:
 Dimensions
Valid keys for suite options are:
 dimensions
 function_idx
 instance_idx

COCO WARNING: coco_observer(): Some keys in observer options were ignored:
 Algorithm_name
Valid keys for observer options are:
 result_folder
 algorithm_name
 algorithm_info
 number_target_triggers
 target_precision
 number_evaluation_triggers
 base_evaluation_triggers
 precision_x
 precision_f
 log_nondominated
 log_decision_variables
 compute_indicators
 produce_all_data
````
Is this OK?

**Comment by ttusar** [comment]
One last thing: what would be a nice plural name for `function_idx` and `instance_idx`?

**Comment by nikohansen** [comment]
Looks pretty good. 

I could think of `functions`, `function_indices`, `function_idxs`.

**Comment by ttusar** [comment]
I always felt `function_indices` are too long, but now seeing it written I see this is the best choice and it's also most in line with the other things we have. I will close this issue when I'm done.

**Comment by ttusar** [comment]
Done.
