### ISSUE TITLE
Calling modified experiments from do.py

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#560]
I'm not sure whether we have already discussed this at some point... Wouldn't it be nice if the users could just say
````
python do.py run-c path/modified_experiment.c
python do.py run-python path/modified_experiment.py
...
````
to run their modified experiment wherever it is? Is there a reason why we couldn't support this?

**Comment by brockho** [comment]
Nice to have, but I am not sure that we can know in advance how to build any code. Already in the Matlab experiments for the SMS-EMOA (and soon the RM-MEDA), the calling script name changes (which is easy to solve now but do we want to impose to the user to always write a `setup.m` for example?). Also for the Java experiments, it's not at all clear how we can automatize the compilation without knowing (or imposing) what the user is implementing.

Hence, from what I remember, we said that the user is supposed to run the `python do.py run-LANGUAGE` once (because the Coco code is not supposed to change) and then typically compiles (if needed) and runs the experiments from within the folder where the experiments lie without using the `do.py` anymore.

**Comment by nikohansen** [comment]
Re python: the idea is that the build has to be done exactly once only. After that, `import cocoex` is all what needs to be added to whichever code wants to use the COCO benchmark suites. 

Re C: the idea was to have `coco.h` and `coco.c` which then users can include in _their own_ workflow. There is no reason to rebuild these over and over again. What is the added value to bind the workflow to `do.py`? What is the added value of calling `do.py` for running an experiment? 

The issue points to a detail which I believe we overlooked: at least in C, the example experiment file cannot be renamed without also changing the MakeFile.

**Comment by ttusar** [comment]
> The issue points to a detail which I believe we overlooked: at least in C, the example experiment file cannot be renamed without also changing the MakeFile. 

Exactly! 

The idea wasn't to build coco again, but to automate the things users needs to do when they move and rename the example experiment. But I see the problem with automatically compiling a modified experiment - it might require more than just a name change...

**Comment by nikohansen** [comment]
Given that workflows are likely to vary to a large extend (a) from user to user and (b) depending on the chosen language, I am closing this issue.
