### ISSUE TITLE
bbob_pproc pprldistr_*.pdf not consistent at different Budgets

### ISSUE THREAD

**Issue by Ulfgard** [numbbo/coco#600]
I have just run an experiment with different budgets (100*dim and 1000*dim). The output I get is not understandable, i would guess that up to "2" both outputs should look exactly the same. Further i do not get the different target values.

Any ideas? Can i provide more plots? (i have not really understood what they mean, i think this is the proportion of trials with function values > some target)

pprldistr_05D_all.pdf @ budget 100
[05D100.pdf](https://github.com/numbbo/coco/files/118983/05D100.pdf)
pprldistr_05D_all.pdf @ budget 1000
[05D1000.pdf](https://github.com/numbbo/coco/files/118982/05D1000.pdf)

**Comment by brockho** [comment]
Dear Oswin.

Many thanks for reporting this. It is indeed confusing to not get the same output on the left of the figure. The reason is that the current postprocessing is choosing a different setting depending on the largest budget among all algorithms you provide. This setting changes, if I am not mistaken, around 100*DIM function evaluations. Above, the standard targets 10^1, ..., 10^{-8} are chosen. Below, the targets depend on the (artificial) best algorithm of BBOB-2009 (the so-called runlength-based targets). 

Issue #566 was filed already to fix the default setting of the postprocessing, independently of the input. If you want to change the behavior deterministically, you should be able to use the `--expensive` and `--not-expensive` flags already now.

In any case, we should have documented this more clearly.
