### ISSUE TITLE
Figure titles should be consistent in font size

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#661]
The new bi-objective plots have the figure titles in various font sizes depending on the overall text length. This will look strange in the LaTeX/PDF format, we will provide and should be fixed. Can't we simply decide on the smallest font among all titles and then use this for all?

**Comment by dtusar** [comment]
Now we have a consistent font size with regard to the longest function name. Check if this is OK. Otherwise we should shorten the function names.

**Comment by dtusar** [comment]
This size is too small for the latex template. In the `html` the font size is OK because the `svg` files are used. When generating the `svg` files this factor is applied: 
`svg_downsize_factor = 0.8`
Because of this factor the header text in the `svg` files is larger (in regard to the image) then in `pdf` files. 
This downsizing has practically no impact on the file size and the generation time. The only difference I see are smaller images which can be achieved also in the `html` file. If there is no other reason for the downsizing then I would suggest that we remove it from the code. Then we can use the same font size for the headers in `pdf `and `svg `files.

**Comment by nikohansen** [comment]
I would really like that the figures stay aligned if I try to get an overview over all results like this: 
<img width="1268" alt="screen shot 2016-02-26 at 2 43 12" src="https://cloud.githubusercontent.com/assets/7316439/13361152/4236b3d4-dcbd-11e5-8635-ab2a35799eea.png">

**Comment by dtusar** [comment]
Solved with #851 The figures are now aligned.
