### ISSUE TITLE
no warning with unknown suite instance

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#700]
In `IPython`: 
```python
In [1]: import cocoex as ex
In [2]: suite = ex.Suite("bbob", "20b", "")
In [3]: len(suite)
Out[3]: 2160
In [4]: ex.log_level()
Out[4]: 'info'
```

I guess an old issue, but how do we solve it?

**Comment by ttusar** [comment]
I thought I took care of this, I will have another look.

**Comment by nikohansen** [comment]
FTR, the situation is the same when I run a respective "mini-script" from `bash`.

**Comment by ttusar** [comment]
Found the problem - the colon is missing. If it said "20b: ss" instead of just "20b", it would show a warning. Right now I'm not sure how much work is needed to fix this more generally (specifically for one key it's easy to fix). As already noted in #490, the current implementation won't catch every possible error in the options.

**Comment by nikohansen** [comment]
Given that

```python
suite = ex.Suite("bbob", "year: 2009", "")
```
is valid option, `ex.Suite("bbob", "2009", "")` or `ex.Suite("bbob", "200b", "")` should better be caught be the checker.

**Comment by ttusar** [comment]
Ok.

**Comment by ttusar** [comment]
Now it should cover most cases (there might still be some not caught).
