### ISSUE TITLE
coco_suite_get_problem crashes when only subset of dimensions is given

### ISSUE THREAD

**Issue by Ulfgard** [numbbo/coco#708]
Hi,

This is a follow up from issue #707. When initializing a suite as

`coco_suite_t* suite = coco_suite("bbob-biobj", "year: 2016", "dimensions: 5");`

and then calling 
`coco_suite_get_problem(suite, 0);`

the program will terminate with an error "COCO FATAL ERROR: coco_allocate_memory() called with 0 size." 

The reason for that is that the first index leads dimension_idx=0 and suite->dimensions[dimension_idx] is 0. Took me a while to figure that out...

**Comment by ttusar** [comment]
@Ulfgard Many thanks for pointing out the two bugs. The fixes are now being tested by the CI and will be pushed to the development branch soon (if everything is ok, that is). 

This quick fix will now make sure that a call to `coco_suite_get_problem` will return NULL if the problem has been filtered out by the suite options. This means that the for loop from #707 will need to check whether the problem is NULL.

**Comment by ttusar** [comment]
Solved.
