### ISSUE TITLE
target dependend figures

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#8]
```
rungeneric should accept a target level for the scaling figures when comparing 
many algorithms. This should work with an f-value and RL based target. 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 8:57

**Comment by brockho** [comment]
I will check whether this is not already possible via `genericsettings.py`.

**Comment by brockho** [comment]
I finally checked the code as promised: for some time now, we can set the displayed target function value in the many algorithm aRT vs. dimension plots via `ppfigs_ftarget` in `testbedsettings.py`. In the case of the expensive setting (aka runlength-based targets), the displayed target runlength has to be chosen in `genericsettings.target_runlength`. In order to better find this setting in the future, I added comments after the occurrences of `ppfigs_ftarget` in `testbedsettings.py` now in the `feature-refalg` branch such that I consider this issue as solved.
