### ISSUE TITLE
Memory Leak in the MatLab wrapper

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#804]
mxFree(cocofunction) is missing in the end of  void mexFunction(...) of cocoCall.c
this leads to memory leaks serious enough to eat the whole memory when long runs are considered

**Comment by brockho** [comment]
Thanks Ilya for letting us know about the bug. One day later, we realized it also ourselves, because we started to test the Matlab code also more extensively now. But you were definitely quicker.

It was fully my fault and should be solved now by pull-request #815 (when I run now the ``exampleexperiment.m`` a couple of times, it does not increase the memory usage anymore on my Windows laptop as it did before). I found also a few other potential memory leaks and removed the corresponding memory allocations because the variables are not used anymore.
