### ISSUE TITLE
Invalid character in Matlab R2015b

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#949]
In ```exampleexperiment.m```, it seems the character ```"``` (double quotation mark) in lines 65, 114 is not a valid character in Matlab R2015b. I must change to the single one, say ```'```, to run experiment.

**Comment by brockho** [comment]
Thanks @NDManh for pointing us to this error. Unfortunately, we only test the Matlab code automatically under Octave at the moment because we do not have Matlab licenses for our continuous integration slaves. And because for Octave single and double quotes are interpreted in the same way, no test complained. I will take care of this.

**Comment by NDManh** [comment]
Also, just a small remark for ```run_smsemoa_on_bbob_biobj.m``` lines 57 and 103.

**Comment by brockho** [comment]
Solved with pull request #953. Will appear in next release.
