### ISSUE TITLE
Recommendations in COCO: a reference is missing

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#955]
http://arxiv.org/pdf/1603.08776.pdf has a section on recommendations, I think that it is missing a reference to its source  (personal communication, http://lists.lri.fr/pipermail/bbob-discuss/2012-March/000191.html and its continuation)

**Comment by nikohansen** [comment]
Re-reading the discussion, in particular [this](http://lists.lri.fr/pipermail/bbob-discuss/2012-March/000192.html) reminded me that recommendations implemented [this way](http://arxiv.org/abs/1603.08776) are rather inappropriate in the noiseless case. Why? Because the possibility to discard an already evaluated solution for the performance assessment *on noiseless problems* does not make sense.

On noiseless problems it seems ultimately necessary to consider both, the evaluated and the recommended solution qualities, in that the to-be-considered quality at a current time step is the minimum (best) of all prior evaluated solutions and the current recommendation, which is then associated with the runtime `t+1`.

**Comment by loshchil** [comment]
About the subject of the ticket:
I do understand that the topic is not of an extraterrestrial origin and so many people with experience in numerical optimization crossed it in one or another way, it also true for many other topics. However, I do believe that the discussion I mentioned had a crucial/kickoff impact on the development of this idea within the COCO. So if things like personal communication should be considered at all, then this is one of the best cases I can find to be documented. I don't think it is a big deal after all to acknowledge a couple of participants of the above-mentioned discussion.

About the recommendation in MO-case:
I probably get it completely wrong. Just a quick check: in the MO case I probably should submit my recommendation of the Pareto set in the decision space. Then, suppose I believe my function is Sphere-Sphere, so I can submit N points to approximate the Pareto set in the decision space. Even if N is limited, I still can submit random points. What will happen in this case? Will you compute their objective function values, find the non-dominated points and compute their hypervolume? Sounds like a hack: if I can submit as many random points I can, some of them will be close to Pareto, especially in 2D. What I just described is all impossible in the current settings, right?
(again, it does not seem to be really that relevant to the SO case where only the optimum is expected to be submitted, the MO case looks different in this respect)

**Comment by ttusar** [comment]
Just to clarify something: the recommendations are not supported yet. The interface exists, but we just didn't have time to actually implement them.

**Comment by nikohansen** [comment]
> Sounds like a hack: if I can submit as many random points I can, some of them will be close to Pareto, especially in 2D. What I just described is all impossible in the current settings, right?

I don't follow. The current specification says that one can replace each evaluated solution with a recommendation. At the same time, one can call the recommendation function an arbitrary number of times, but only the last call before the next evaluation counts. That is, one can submit only exactly as many points as one has evaluated.

Having said that, I am not entirely convinced that this is the best way to proceed, but I also can't present a candidate which is obviously superior to this methodology. The problem in the MO case is that returning a large *unevaluated* Pareto approximation set is of significant *less value* than returning an already evaluated approximation set.

**Comment by loshchil** [comment]
recommendation in the MO case is to provide the whole Pareto set and not one solution, would you agree on that? 
if yes, then if the number of solutions of the recommended Pareto is not bounded, then I can provide a lot of random points and still be good

**Comment by brockho** [comment]
I don't agree that providing an unbounded estimate of the Pareto front should be allowed as a recommendation. The number of recommended solutions must always be, at least, upper bounded by the number of evaluations done so far. In other words, you cannot replace more points than you have evaluated so far.

At the moment, we decided to make no difference between the multi-objective and the single-objective case in terms of recommendations (see @nikohansen's answer above). Already recording all non-dominated points turned out to produce too much data (see #905) - adding the potential of sets of recommendations at any time as large as all that has been evaluated so far seems a bit too much to record.

**Comment by loshchil** [comment]
I didn't propose to provide an unbounded estimate, on the contrary, I pointed out that it is problematic and would lead to a hack. 
Not sure the number of the provided points should have something to do with the number of evaluations done so far, one can make potentially good/precise predictions only after very few evaluations.

If you use hypervolume only, then you can just compute it based on the current collected points or based on the recommended points provided by the user. You can abandon data logging for recommendations.

**Comment by nikohansen** [comment]
> recommendation in the MO case is to provide the whole Pareto set and not one solution, would you agree on that? 

good point, though I believe it does not (see [here](http://numbbo.github.io/coco-doc/C/coco_8h.html#afd76a19eddd49fb78c22563390437df2) for the current interface), at least not anymore. 

> if yes, then if the number of solutions of the recommended Pareto is not bounded

this would certainly be an unsustainable situation and we should keep in mind to not (mistakenly) allow this, if we decide to change the current interface.

**Comment by loshchil** [comment]
The reference is still missing.
