### ISSUE TITLE
Improved handling of different testbeds

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#978]
We should asap clean up the way testbeds are detected and handled:
- the name of the file where the reference algorithm is stored should become part of the Testbed class
- `config.config` should not take an argument anymore but should detect itself which testbed should be loaded
- `pproc.TargetValues` should not be a parameter of loadCurrentTestbed(...) anymore

In order to proceed with the constrained test suite, item 1 should be of the highest priority.

**Comment by dtusar** [comment]
>  the name of the file where the reference algorithm is stored should become part of the Testbed class

This is done.

> config.config should not take an argument anymore but should detect itself which testbed should be loaded

The information about the testbed comes from the dataset, so we still have an argument. But instead of a `boolean `we now have the `string `argument with the name of the testbed.

> pproc.TargetValues should not be a parameter of loadCurrentTestbed(...) anymore

Testbed data was moved to `testbedsettings.py` but the argument `target_values` stays for now because of the cyclic imports.
